// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: eigenlayer/rewards_service/v1/api.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Rewards_GenerateClaimProof_FullMethodName       = "/eigenlayer.apis.api.v1.Rewards/GenerateClaimProof"
	Rewards_GetEarnedTokensForEarner_FullMethodName = "/eigenlayer.apis.api.v1.Rewards/GetEarnedTokensForEarner"
)

// RewardsClient is the client API for Rewards service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RewardsClient interface {
	GenerateClaimProof(ctx context.Context, in *GenerateClaimProofRequest, opts ...grpc.CallOption) (*GenerateClaimProofResponse, error)
	GetEarnedTokensForEarner(ctx context.Context, in *GetEarnedTokensForEarnerRequest, opts ...grpc.CallOption) (*GetEarnedTokensForEarnerResponse, error)
}

type rewardsClient struct {
	cc grpc.ClientConnInterface
}

func NewRewardsClient(cc grpc.ClientConnInterface) RewardsClient {
	return &rewardsClient{cc}
}

func (c *rewardsClient) GenerateClaimProof(ctx context.Context, in *GenerateClaimProofRequest, opts ...grpc.CallOption) (*GenerateClaimProofResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateClaimProofResponse)
	err := c.cc.Invoke(ctx, Rewards_GenerateClaimProof_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rewardsClient) GetEarnedTokensForEarner(ctx context.Context, in *GetEarnedTokensForEarnerRequest, opts ...grpc.CallOption) (*GetEarnedTokensForEarnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEarnedTokensForEarnerResponse)
	err := c.cc.Invoke(ctx, Rewards_GetEarnedTokensForEarner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RewardsServer is the server API for Rewards service.
// All implementations should embed UnimplementedRewardsServer
// for forward compatibility.
type RewardsServer interface {
	GenerateClaimProof(context.Context, *GenerateClaimProofRequest) (*GenerateClaimProofResponse, error)
	GetEarnedTokensForEarner(context.Context, *GetEarnedTokensForEarnerRequest) (*GetEarnedTokensForEarnerResponse, error)
}

// UnimplementedRewardsServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRewardsServer struct{}

func (UnimplementedRewardsServer) GenerateClaimProof(context.Context, *GenerateClaimProofRequest) (*GenerateClaimProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateClaimProof not implemented")
}
func (UnimplementedRewardsServer) GetEarnedTokensForEarner(context.Context, *GetEarnedTokensForEarnerRequest) (*GetEarnedTokensForEarnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEarnedTokensForEarner not implemented")
}
func (UnimplementedRewardsServer) testEmbeddedByValue() {}

// UnsafeRewardsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RewardsServer will
// result in compilation errors.
type UnsafeRewardsServer interface {
	mustEmbedUnimplementedRewardsServer()
}

func RegisterRewardsServer(s grpc.ServiceRegistrar, srv RewardsServer) {
	// If the following call pancis, it indicates UnimplementedRewardsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rewards_ServiceDesc, srv)
}

func _Rewards_GenerateClaimProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateClaimProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RewardsServer).GenerateClaimProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rewards_GenerateClaimProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RewardsServer).GenerateClaimProof(ctx, req.(*GenerateClaimProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rewards_GetEarnedTokensForEarner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEarnedTokensForEarnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RewardsServer).GetEarnedTokensForEarner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rewards_GetEarnedTokensForEarner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RewardsServer).GetEarnedTokensForEarner(ctx, req.(*GetEarnedTokensForEarnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Rewards_ServiceDesc is the grpc.ServiceDesc for Rewards service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rewards_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eigenlayer.apis.api.v1.Rewards",
	HandlerType: (*RewardsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateClaimProof",
			Handler:    _Rewards_GenerateClaimProof_Handler,
		},
		{
			MethodName: "GetEarnedTokensForEarner",
			Handler:    _Rewards_GetEarnedTokensForEarner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eigenlayer/rewards_service/v1/api.proto",
}
